sudo: required
dist: trusty

language: scala

addons:
  firefox: latest
  chrome: stable

before_script:
  # Instal google-chrome-driver
  - wget http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PWD/chromedriver:$PATH
  # Instal firefox-driver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PWD/geckodriver:$PATH

script:
  - xvfb-run sbt ++$TRAVIS_SCALA_VERSION $TEST_PACKAGE

jdk:
  - oraclejdk8

scala:
  - 2.11.12
  - 2.12.7

env:
  - TEST_PACKAGE="core-macros/test core-shared/test core-shared-JS/test core-frontend/test"
  - TEST_PACKAGE="rpc-shared/test rpc-shared-JS/test rpc-backend/test rpc-frontend/test"
  - TEST_PACKAGE="rest-macros/test rest-shared/test rest-shared-JS/test rest-backend/test"
  - TEST_PACKAGE="i18n-shared/test i18n-shared-JS/test i18n-backend/test i18n-frontend/test"
  - TEST_PACKAGE="auth-shared/test auth-shared-JS/test auth-frontend/test"
  - TEST_PACKAGE="css-macros/test css-shared/test css-shared-JS/test css-backend/test css-frontend/test"
  - TEST_PACKAGE="bootstrap/test"
  - TEST_PACKAGE="bootstrap4/test"
  - TEST_PACKAGE="charts/test"
  - TEST_PACKAGE="benchmarks-frontend/compile"
  - TEST_PACKAGE="selenium-backend/test"