sudo: required
dist: trusty

language: scala

addons:
  chrome: stable

before_script:
  # Install google-chrome-driver
  - wget http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PWD/chromedriver:$PATH

script:
  - cd $TEST_DIR
  - xvfb-run sbt ++$TRAVIS_SCALA_VERSION $TEST_PACKAGE

jdk:
  - oraclejdk8
scala:
  - 2.11.12
  - 2.12.8

env:
  matrix:
    - TEST_DIR=. TEST_PACKAGE="utils/test utils-js/test"
    - TEST_DIR=. TEST_PACKAGE="core/test core-js/test"
    - TEST_DIR=. TEST_PACKAGE="rpc/test rpc-js/test"
    - TEST_DIR=. TEST_PACKAGE="rest/test rest-js/test"
    - TEST_DIR=. TEST_PACKAGE="i18n/test i18n-js/test"
    - TEST_DIR=. TEST_PACKAGE="auth/test auth-js/test"
    - TEST_DIR=. TEST_PACKAGE="css/test css-js/test"
    - TEST_DIR=. TEST_PACKAGE="bootstrap/test"
    - TEST_DIR=. TEST_PACKAGE="bootstrap4/test"
    - TEST_DIR=. TEST_PACKAGE="charts/test"
    - TEST_DIR=. TEST_PACKAGE="benchmarks/compile"
    - TEST_DIR=. TEST_PACKAGE="selenium/test"
    - TEST_DIR=. TEST_PACKAGE="doc"
    - TEST_DIR=guide TEST_PACKAGE="selenium/test"

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.coursier/cache
  - $HOME/.sbt/boot/
  - $HOME/.sbt/launchers/
