sudo: required
dist: trusty
addons:
  chrome: stable
language: scala

before_script:
  # Install Selenium chromedriver
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d selenium-bin
  - export PATH=$PWD/selenium-bin:$PATH

jdk:
  - oraclejdk8

scala:
  - 2.11.11
  - 2.12.4

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION selenium/test